# Generated by Django 2.0 on 2018-03-10 01:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('comments', '0001_initial')]

    operations = [
        migrations.AlterModelOptions(
            name='comment', options={'ordering': ['-created_at']}
        )
    ]
