# Generated by Django 2.0 on 2018-02-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('accounts', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(
                blank=True, null=True, verbose_name='Descrição do usuário'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=20, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=15, null=True, verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.URLField(
                blank=True, max_length=150, null=True, verbose_name='Foto do perfil'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=3, null=True, verbose_name='Estado'),
        ),
    ]
