# Generated by Django 2.0 on 2018-02-21 02:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('accounts', '0005_auto_20180221_0104')]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_friends_ids',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, null=True, size=None
            ),
        )
    ]
