# Generated by Django 2.0 on 2018-02-21 21:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('accounts', '0006_user_facebook_friends_ids')]

    operations = [
        migrations.RemoveField(model_name='user', name='facebook_friends_ids')
    ]
