# Generated by Django 2.0 on 2018-02-21 21:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_facebook_friends_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_friends_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='facebook_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
