# Generated by Django 2.0 on 2018-03-16 21:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('accounts', '0012_user_birthday')]

    operations = [migrations.RemoveField(model_name='user', name='birthday')]
