# Generated by Django 2.0 on 2018-04-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='is_active',
        ),
        migrations.AddField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[(0, 'ios'), (1, 'android')], default=1, max_length=10),
        ),
    ]
