# Generated by Django 2.0 on 2018-04-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0003_auto_20180408_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='one_signal_player_id',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
