# Generated by Django 2.0 on 2018-03-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulsos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pulso',
            options={'ordering': ['-ends_at']},
        ),
        migrations.AlterField(
            model_name='pulso',
            name='radius',
            field=models.IntegerField(default=10, help_text='distância em metros'),
        ),
    ]
