# Generated by Django 2.0 on 2018-03-16 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulsos', '0004_auto_20180309_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pulso',
            options={'ordering': ['ends_at']},
        ),
    ]
